export const PHARMA_UNITS: string[] = [
  "Ampoule",
  "Bottle",
  "Box",
  "Capsule",
  "Cartridge",
  "Drop(s)",
  "Enema",
  "Gel (tube)",
  "Gram",
  "Implant",
  "Inhaler",
  "Kilogram",
  "Liter",
  "Lozenge",
  "Milligram",
  "Milliliter",
  "Ointment (tube)",
  "Patch",
  "Pessary",
  "Powder (sachet)",
  "Pre-filled syringe",
  "Sachet",
  "Solution (bottle)",
  "Strip / Blister",
  "Suppository",
  "Suspension (bottle)",
  "Syrup (bottle)",
  "Tablet",
  "Unit",
  "Vial",
];

export const PHARMA_CATEGORIES: string[] = [
  "Analgesic / Antipyretic",
  "Anesthetic",
  "Antiallergic / Antihistamine",
  "Antianemic",
  "Antianxiety / Anxiolytic",
  "Antibiotic",
  "Anticoagulant / Antithrombotic",
  "Antidepressant",
  "Antidiabetic",
  "Antiemetic",
  "Antiepileptic / Anticonvulsant",
  "Antifungal",
  "Antihypertensive",
  "Antiparasitic / Antiprotozoal",
  "Antipsychotic",
  "Antispasmodic",
  "Antituberculous",
  "Antiviral",
  "Cardiovascular",
  "Contraceptive",
  "Corticosteroid",
  "Dermatological",
  "Diuretic",
  "Electrolyte / IV Fluid",
  "Gastrointestinal",
  "Hematological",
  "Hepatic / Liver",
  "Immunological / Vaccine",
  "Immunosuppressant",
  "Laxative",
  "Muscle Relaxant",
  "Neurological",
  "NSAID",
  "Nutritional Supplement",
  "Oncology / Antineoplastic",
  "Ophthalmological",
  "Pulmonary / Respiratory",
  "Renal / Urological",
  "Thyroid",
  "Vitamins & Minerals",
  "Wound Care / Antiseptic",
  "Supplies",
  "Equipment",
  "Flu Med",
  "Others",
];
